---
# COPY this file to secrets.yml

development:
  APP_URL: http://localhost:9292
  MSG_KEY: QwsjC6WdxnNYjiWn5qOFp4xBRFcWY+wjrARjV0Vz3cA=
  APP_MSG_KEY: gwsDllBHxjSaUQQjvEL9UuDTnkgOwzF/IrOne2Ec4/Y=
  DB_KEY: pFrP9v4qQNRvpEeLl4RL0s8C3pmMyOKTYrjHhb2rq4g=
  SIGNING_KEY: FVxMGwdIgV1NZCk8L63kTpe/Pi9eUQhHou0AJVnNmcM=
  VERIFY_KEY: SsXPp6bnlS0Jwjck+gZwsC0k274Egb6t0t+bVcKocMI=
  DATABASE_URL: sqlite://app/db/store/development.db
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  SECURE_SCHEME: HTTP

test:
  APP_URL: http://localhost:9292
  MSG_KEY: QwsjC6WdxnNYjiWn5qOFp4xBRFcWY+wjrARjV0Vz3cA=
  APP_MSG_KEY: gwsDllBHxjSaUQQjvEL9UuDTnkgOwzF/IrOne2Ec4/Y=
  DB_KEY: pFrP9v4qQNRvpEeLl4RL0s8C3pmMyOKTYrjHhb2rq4g=
  SIGNING_KEY: FVxMGwdIgV1NZCk8L63kTpe/Pi9eUQhHou0AJVnNmcM=
  VERIFY_KEY: SsXPp6bnlS0Jwjck+gZwsC0k274Egb6t0t+bVcKocMI=
  DATABASE_URL: sqlite://app/db/store/test.db
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  SECURE_SCHEME: HTTP

production:
  APP_URL: http://localhost:9292
  MSG_KEY: <`rake new_key:msg`>
  APP_MSG_KEY: <`MSG KEY for web app`>
  DB_KEY: <`rake new_key:db`>
  SIGNING_KEY: <`rake newkey:signing`> # needed by client app; used in api tests
  VERIFY_KEY: <`rake newkey:signing`>
  DATABASE_URL: <do not edit - allow production server to set>
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  SECURE_SCHEME: HTTPS
